services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - JAEGER_ENDPOINT=otel-collector:4317
    restart: unless-stopped
    entrypoint: poetry run fastapi run jopaper/api.py

  cli:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    volumes:
      - ./:/out
    profiles: [cli]
    entrypoint: poetry run python -m jopaper --path /out/wallpaper.png

  jaeger-collector:
    image: jaegertracing/jaeger-collector:${JAEGER_VERSION}
    command:
      - "--cassandra.keyspace=${CASSANDRA_KEYSPACE}"
      - "--cassandra.servers=cassandra"
      - "--collector.otlp.enabled=true"
    environment:
      - SAMPLING_CONFIG_TYPE=adaptive
    restart: unless-stopped
    depends_on:
      - cassandra-schema

  cassandra:
    image: cassandra:5.0.2

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:${JAEGER_VERSION}
    environment:
      - KEYSPACE=${CASSANDRA_KEYSPACE}

  jaeger-query:
    image: jaegertracing/jaeger-query:${JAEGER_VERSION}
    environment:
      - METRICS_STORAGE_TYPE=prometheus
    command:
      - "--cassandra.keyspace=${CASSANDRA_KEYSPACE}"
      - "--cassandra.servers=cassandra"
      - "--prometheus.server-url=http://prometheus:9090"
      - "--prometheus.query.normalize-duration=true"
      - "--prometheus.query.normalize-calls=true"
    ports:
      - "16686:16686"
    restart: unless-stopped
    depends_on:
      - cassandra-schema

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.116.1
    restart: unless-stopped
    command:
      - "--config=/config.yml"
    volumes:
      - ./config/otel-collector/config.yml:/config.yml
    depends_on:
      - jaeger-collector

  prometheus:
    image: prom/prometheus:v2.51.2
    command:
      - "--config.file=/config.yml"
    volumes:
      - ./config/prometheus/config.yml:/config.yml
